/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminResourcesRouteImport } from './routes/admin/resources'
import { Route as AdminProfileRouteImport } from './routes/admin/profile'
import { Route as AdminMembersRouteImport } from './routes/admin/members'
import { Route as AdminFaqsRouteImport } from './routes/admin/faqs'
import { Route as AdminEventsRouteImport } from './routes/admin/events'
import { Route as AdminContactInfoRouteImport } from './routes/admin/contact-info'
import { Route as AdminBlogsRouteImport } from './routes/admin/blogs'
import { Route as AdminArchivesRouteImport } from './routes/admin/archives'
import { Route as AdminAlumnisRouteImport } from './routes/admin/alumnis'
import { Route as AdminAdminUsersRouteImport } from './routes/admin/admin-users'
import { Route as AdminLayoutRouteImport } from './routes/admin/_layout'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthAddUserRouteImport } from './routes/_auth/add-user'
import { Route as ApiTrpcSplatRouteImport } from './routes/api.trpc.$'

const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminResourcesRoute = AdminResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminProfileRoute = AdminProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminMembersRoute = AdminMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminFaqsRoute = AdminFaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminEventsRoute = AdminEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminContactInfoRoute = AdminContactInfoRouteImport.update({
  id: '/contact-info',
  path: '/contact-info',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminBlogsRoute = AdminBlogsRouteImport.update({
  id: '/blogs',
  path: '/blogs',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminArchivesRoute = AdminArchivesRouteImport.update({
  id: '/archives',
  path: '/archives',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAlumnisRoute = AdminAlumnisRouteImport.update({
  id: '/alumnis',
  path: '/alumnis',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAdminUsersRoute = AdminAdminUsersRouteImport.update({
  id: '/admin-users',
  path: '/admin-users',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLayoutRoute = AdminLayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/_auth/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAddUserRoute = AuthAddUserRouteImport.update({
  id: '/_auth/add-user',
  path: '/add-user',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminLayoutRoute
  '/add-user': typeof AuthAddUserRoute
  '/login': typeof AuthLoginRoute
  '/admin/admin-users': typeof AdminAdminUsersRoute
  '/admin/alumnis': typeof AdminAlumnisRoute
  '/admin/archives': typeof AdminArchivesRoute
  '/admin/blogs': typeof AdminBlogsRoute
  '/admin/contact-info': typeof AdminContactInfoRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/faqs': typeof AdminFaqsRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/resources': typeof AdminResourcesRoute
  '/admin/': typeof AdminIndexRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add-user': typeof AuthAddUserRoute
  '/login': typeof AuthLoginRoute
  '/admin': typeof AdminIndexRoute
  '/admin/admin-users': typeof AdminAdminUsersRoute
  '/admin/alumnis': typeof AdminAlumnisRoute
  '/admin/archives': typeof AdminArchivesRoute
  '/admin/blogs': typeof AdminBlogsRoute
  '/admin/contact-info': typeof AdminContactInfoRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/faqs': typeof AdminFaqsRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/resources': typeof AdminResourcesRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/_auth/add-user': typeof AuthAddUserRoute
  '/_auth/login': typeof AuthLoginRoute
  '/admin/_layout': typeof AdminLayoutRoute
  '/admin/admin-users': typeof AdminAdminUsersRoute
  '/admin/alumnis': typeof AdminAlumnisRoute
  '/admin/archives': typeof AdminArchivesRoute
  '/admin/blogs': typeof AdminBlogsRoute
  '/admin/contact-info': typeof AdminContactInfoRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/faqs': typeof AdminFaqsRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/resources': typeof AdminResourcesRoute
  '/admin/': typeof AdminIndexRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/add-user'
    | '/login'
    | '/admin/admin-users'
    | '/admin/alumnis'
    | '/admin/archives'
    | '/admin/blogs'
    | '/admin/contact-info'
    | '/admin/events'
    | '/admin/faqs'
    | '/admin/members'
    | '/admin/profile'
    | '/admin/resources'
    | '/admin/'
    | '/api/trpc/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/add-user'
    | '/login'
    | '/admin'
    | '/admin/admin-users'
    | '/admin/alumnis'
    | '/admin/archives'
    | '/admin/blogs'
    | '/admin/contact-info'
    | '/admin/events'
    | '/admin/faqs'
    | '/admin/members'
    | '/admin/profile'
    | '/admin/resources'
    | '/api/trpc/$'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/_auth/add-user'
    | '/_auth/login'
    | '/admin/_layout'
    | '/admin/admin-users'
    | '/admin/alumnis'
    | '/admin/archives'
    | '/admin/blogs'
    | '/admin/contact-info'
    | '/admin/events'
    | '/admin/faqs'
    | '/admin/members'
    | '/admin/profile'
    | '/admin/resources'
    | '/admin/'
    | '/api/trpc/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AuthAddUserRoute: typeof AuthAddUserRoute
  AuthLoginRoute: typeof AuthLoginRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/resources': {
      id: '/admin/resources'
      path: '/resources'
      fullPath: '/admin/resources'
      preLoaderRoute: typeof AdminResourcesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/profile': {
      id: '/admin/profile'
      path: '/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminProfileRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/members': {
      id: '/admin/members'
      path: '/members'
      fullPath: '/admin/members'
      preLoaderRoute: typeof AdminMembersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/faqs': {
      id: '/admin/faqs'
      path: '/faqs'
      fullPath: '/admin/faqs'
      preLoaderRoute: typeof AdminFaqsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/events': {
      id: '/admin/events'
      path: '/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AdminEventsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/contact-info': {
      id: '/admin/contact-info'
      path: '/contact-info'
      fullPath: '/admin/contact-info'
      preLoaderRoute: typeof AdminContactInfoRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/blogs': {
      id: '/admin/blogs'
      path: '/blogs'
      fullPath: '/admin/blogs'
      preLoaderRoute: typeof AdminBlogsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/archives': {
      id: '/admin/archives'
      path: '/archives'
      fullPath: '/admin/archives'
      preLoaderRoute: typeof AdminArchivesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/alumnis': {
      id: '/admin/alumnis'
      path: '/alumnis'
      fullPath: '/admin/alumnis'
      preLoaderRoute: typeof AdminAlumnisRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/admin-users': {
      id: '/admin/admin-users'
      path: '/admin-users'
      fullPath: '/admin/admin-users'
      preLoaderRoute: typeof AdminAdminUsersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/_layout': {
      id: '/admin/_layout'
      path: ''
      fullPath: '/admin'
      preLoaderRoute: typeof AdminLayoutRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/add-user': {
      id: '/_auth/add-user'
      path: '/add-user'
      fullPath: '/add-user'
      preLoaderRoute: typeof AuthAddUserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteRouteChildren {
  AdminLayoutRoute: typeof AdminLayoutRoute
  AdminAdminUsersRoute: typeof AdminAdminUsersRoute
  AdminAlumnisRoute: typeof AdminAlumnisRoute
  AdminArchivesRoute: typeof AdminArchivesRoute
  AdminBlogsRoute: typeof AdminBlogsRoute
  AdminContactInfoRoute: typeof AdminContactInfoRoute
  AdminEventsRoute: typeof AdminEventsRoute
  AdminFaqsRoute: typeof AdminFaqsRoute
  AdminMembersRoute: typeof AdminMembersRoute
  AdminProfileRoute: typeof AdminProfileRoute
  AdminResourcesRoute: typeof AdminResourcesRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminLayoutRoute: AdminLayoutRoute,
  AdminAdminUsersRoute: AdminAdminUsersRoute,
  AdminAlumnisRoute: AdminAlumnisRoute,
  AdminArchivesRoute: AdminArchivesRoute,
  AdminBlogsRoute: AdminBlogsRoute,
  AdminContactInfoRoute: AdminContactInfoRoute,
  AdminEventsRoute: AdminEventsRoute,
  AdminFaqsRoute: AdminFaqsRoute,
  AdminMembersRoute: AdminMembersRoute,
  AdminProfileRoute: AdminProfileRoute,
  AdminResourcesRoute: AdminResourcesRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AuthAddUserRoute: AuthAddUserRoute,
  AuthLoginRoute: AuthLoginRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
